baseURL = 'https://databrickslabs.github.io/dlt-meta/'
languageCode = 'en-us'
title = 'DLT-META'
theme= "hugo-theme-relearn"
pluralizeListTitles = false
canonifyURLs = true

[params]
    themeVariant = 'learn'
    themeVariantAuto = 'learn'
    disableShortcutsTitle = true
    disableLandingPageButton = false
    description = "DLT-META Documentation"
    author.name = "Ravi Gawai (Databricks)"
    disableNextPrev = false